spring:
  application:
    name: hr_bank
  profiles:
    active: dev

springdoc:
  api-docs:
    # OpenAPI ??? ??(JSON)
    path: /v3/api-docs
  swagger-ui:
    # OpenAPI ??? ??(HTML)
    path: /swagger-ui.html
    # ?? ?? ?? ??
    display-request-duration: true
    # API ?? ??
    operations-sorter: method   # HTTP ???? ??? ??
  #    operations-sorter: alpha    # Java ???? ??? ??

# ?? ??
logging:
  level:
    # ???? SQL ??
    org.hibernate.SQL: debug
    # ????? ???? ??
    org.hibernate.orm.jdbc.bind: trace

# ?? ?? ?? ??
hr-bank:
  file_directories:
    profiles: .profiles
    backups: .backups
    logs: .logs