spring:
  application:
    name: hr_bank
  profiles:
    active: dev

  # H2 데이터베이스 및 콘솔 설정
  h2:
    console:
      enabled: true            # 웹에서 DB를 볼 수 있게 활성화
      path: /h2-console        # 접속 주소: http://localhost:8080/h2-console

  datasource:
    url: jdbc:h2:mem:testdb    # 메모리 DB 주소 (서버 재시작 시 초기화됨)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 및 Hibernate 로그 설정
  jpa:
    hibernate:
      ddl-auto: update         # 엔티티 변경사항을 DB 테이블에 자동 반영
    show-sql: true             # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true       # SQL 로그를 가독성 좋게 포맷팅
        highlight_sql: true    # SQL 로그에 하이라이팅 적용

# Swagger(SpringDoc) 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

# 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # SQL 파라미터 바인딩 값 확인용

# 프로젝트 커스텀 설정
hr-bank:
  file_directories:
    profiles: .profiles
    backups: .backups
    logs: .logs