spring:
  application:
    name: hr_bank

  # JPA 및 Hibernate 로그 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      leak-detection-threshold: 60000

# Swagger(SpringDoc) 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method

# 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace # SQL 파라미터 바인딩 값 확인용

# 프로젝트 커스텀 설정
hr-bank:
  file_directories:
    profiles: ./profiles
    backups: ./backups
    logs: ./logs

backup:
  batch:
    schedule:
      cron: "0 0 * * * *"